	
service: sls-aws-spring-cloud-function
provider:
  name: aws
  runtime: java11
  timeout: 30
package:
  artifact: target/aws-java-spring-cloud-function-demo-0.0.1-SNAPSHOT-aws.jar
functions:
  members:
    handler: com.healthfirst.memberfunction.AwsLambdaHandler
    environment:
      FUNCTION_NAME: members