service: sls-aws-spring-cloud-function
provider:
  name: aws
  runtime: java11
  timeout: 30
package:
  artifact: production/rabbitmq-tutorials-0.0.2-RELEASE-${GITHUB_SHA::6}.jar
functions:
  members:
    handler: com.healthfirst.memberfunction.AwsLambdaHandler
    environment:
      FUNCTION_NAME: members