name: building java spring and deploy on aws
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "infrastructure/**"
      - "README.md"
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy_spring:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActions
          audience: sts.amazonaws.com
          aws-region: sa-east-1
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build package
        run: mvn versions:set -DnewVersion=0.0.2-${GITHUB_SHA::6}-RELEASE && mvn --batch-mode clean deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_DEPLOY_TOKEN }}
      - run: mkdir production && cp target/*.jar production
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: core-services
          path: production
          retention-days: 15
      - name: upload jar on bucket s3
        uses: reggionick/s3-deploy@v3
        with:
          folder: production
          bucket: core-prod-store-jar
          bucket-region: sa-east-1
          delete-removed: true
      # - name: notification on microsoft teams
      #   uses: toko-bifrost/ms-teams-deploy-card@master
      #   if: always()
      #   with:
      #     github-token: ${{ secrets.JAVA_DEPLOY_TOKEN }}
      #     webhook-uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
      #     timezone: America/Argentina/Buenos_Aires
