name: building java spring and deploy on aws
on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  provisioning:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit
