name: preview to main
on:
  pull_request:
    branches: [main]
jobs:
  build_on_pr:
    runs-on: ubuntu-latest
    environment:
      name: preview
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: ./workflows/reusables/setup_java.yml
        with:
          environment: preview
      - uses: ./workflows/reusables/maven_tests.yml
        with:
          environment: preview
