name: Setup Java with POM

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActions
          audience: sts.amazonaws.com
          aws-region: sa-east-1
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: adopt
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
