name: Setup Java with POM

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
      - name: Terraform Plan
        id: plan
        run: |
          cd infrastructure/terraform
          terraform plan -var-file=productin.tfvars
      - name: Submit plan for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        id: submit_plan
        with:
          command: submit
          plan_contents: ${{steps.plan.outputs.stdout}}
      - name: Wait for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        with:
          command: wait
          plan_id: ${{steps.submit_plan.outputs.plan_id}}
          timeout_seconds: 1200
      - name: Terraform Apply
        run: |
          cd infrastructure/terraform
          terraform apply -auto-approve terraform_production.tfplan
