name: deploy terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActions
          audience: sts.amazonaws.com
          aws-region: sa-east-1
      - name: setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
      - name: Terraform Init
        run: terraform -chdir="./infrastructure/terraform" init -input=false
      - name: Terraform Plan
        id: plan
        run: terraform -chdir="./infrastructure/terraform" plan -var-file=production.tfvars -no-color
      - name: Submit plan for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        id: submit_plan
        with:
          command: submit
          plan_contents: ${{steps.plan.outputs.stdout}}
      - name: Wait for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        with:
          command: wait
          plan_id: ${{steps.submit_plan.outputs.plan_id}}
          timeout_seconds: 1200
      - name: Terraform Apply
        run: terraform -chdir="./infrastructure/terraform" apply -auto-approve terraform_production.tfplan
