name: Terraform Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: GitHubActions
        audience: sts.amazonaws.com
        aws-region: sa-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.1.7"

    - name: Install Checkov
      run: pip install checkov

    - name: Terraform init
      run: terraform -chdir="./infrastructure/terraform" init -input=false

    - name: Terraform Plan
      id: terraform_plan
      run: terraform -chdir="./infrastructure/terraform" plan -var-file=production.tfvars -no-color -out=tfplan
      env:
        TF_VAR_auto_approve: 0

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      run: terraform -chdir="./infrastructure/terraform" apply tfplan
      env:
        TF_VAR_auto_approve: 1
